"""Discovery data models -- auto-detected emerging themes."""
from datetime import datetime, timezone
from typing import Literal
from uuid import uuid4

from pydantic import BaseModel, Field


class DiscoveredTheme(BaseModel):
    """A single automatically-discovered thematic cluster.

    Generated by the Discovery engine via broad GitHub search + LLM clustering.
    """
    topic: str                                    # e.g. "ai-native-terminal"
    description: str                              # LLM-generated one-liner
    repo_count: int                               # repos in this cluster
    avg_stars: float                              # average star count
    velocity: float                               # aggregate growth velocity
    stage: Literal["emerging", "accelerating", "stable", "cooling"]
    sample_repos: list[str] = Field(default_factory=list)  # top 3 full_names
    is_new: bool = True                           # False if already in config domains
    suggested_as_topic: bool = True               # worth adding to tracking config


class DiscoverySnapshot(BaseModel):
    """A snapshot of auto-discovered themes for one discovery cycle."""
    id: str = Field(default_factory=lambda: uuid4().hex[:8])
    domain: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    window_days: int = 60
    themes: list[DiscoveredTheme] = Field(default_factory=list)
