"""Schema-enforced output models for all sandbox commands.

Every command outputs a SandboxResult wrapper containing typed payload data.
Claude Code reads these JSON outputs — the schemas here are the contract.

All Field definitions carry `description=` metadata for downstream agent consumption,
enabling ASI (Actionable Side Information) — agents understand field semantics and
constraints without reading external documentation.
"""
from datetime import datetime, timezone
from typing import Any, Literal

from pydantic import BaseModel, Field


class DataQualityDiag(BaseModel):
    """Data quality diagnostics — is the input data sufficient and reliable?"""
    coverage_gaps: list[str] = Field(
        default_factory=list,
        description="Topics, queries, or areas that matched too few results (below significance threshold)",
    )
    noise_sources: list[str] = Field(
        default_factory=list,
        description="Sources of noise: overly broad queries, irrelevant matches, stale cache data",
    )
    api_issues: list[str] = Field(
        default_factory=list,
        description="API-related problems: rate limits, retry exhaustions, empty responses, auth errors",
    )
    sample_size_warning: str = Field(
        default="",
        description="Human-readable warning when total sample size is below the significance threshold for reliable conclusions",
    )


class ConfidenceDiag(BaseModel):
    """Confidence diagnostics — which conclusions are unreliable and why?"""
    low_confidence_items: list[dict] = Field(
        default_factory=list,
        description="Items whose confidence is below the acceptable threshold. Each dict has keys: item, confidence, reason",
    )
    high_variance_items: list[dict] = Field(
        default_factory=list,
        description="Items whose metrics show high variance across runs or within the dataset. Each dict has keys: item, variance, reason",
    )


class ParamSensitivity(BaseModel):
    """Parameter sensitivity hint — what would happen if we changed a parameter?

    Generated by the observability module by comparing snapshots across runs.
    Used by the optimize skill to propose concrete parameter adjustments.
    """
    parameter: str = Field(description="Name of the parameter to adjust (e.g. 'config.domains.agent.topics')")
    current_value: str = Field(description="Current value of the parameter")
    suggested_value: str = Field(description="Suggested new value for the parameter")
    expected_effect: str = Field(description="Human-readable description of the expected impact")
    confidence: float = Field(default=0.5, description="Confidence in this suggestion (0-1), based on historical evidence")


class Diagnostics(BaseModel):
    """Actionable diagnostics attached to every SandboxResult.

    Three diagnostic dimensions:
      - data_quality: Is the input data good enough?
      - confidence: Which conclusions should be treated skeptically?
      - parameter_sensitivity: What parameter changes might improve results?

    These are the ASI (Actionable Side Information) that enable Claude Code
    to go beyond reading results — it can now understand WHY results may be
    suboptimal and HOW to improve them.
    """
    data_quality: DataQualityDiag = Field(default_factory=DataQualityDiag)
    confidence: ConfidenceDiag = Field(default_factory=ConfidenceDiag)
    parameter_sensitivity: list[ParamSensitivity] = Field(default_factory=list)


class SandboxResult(BaseModel):
    """Every sandbox command wraps its output in this."""
    command: str = Field(description="CLI command name that produced this result: collect, trend, pain, opportunity, report, config, observability")
    domain: str = Field(description="Domain being analyzed (e.g. 'agent', 'devtools', 'consumer', 'infrastructure')")
    computed_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat(), description="ISO 8601 timestamp when this result was produced")
    payload: dict[str, Any] = Field(description="Command-specific output data — schema depends on command type. See TopicTrend, PainCluster, OpportunityCard, etc.")
    stats: dict[str, Any] = Field(default_factory=dict, description="Aggregate statistics: counts, elapsed time, cache metrics, API usage")
    diagnostics: Diagnostics = Field(default_factory=Diagnostics, description="Actionable diagnostics for the optimize skill: data quality issues, confidence warnings, parameter sensitivity hints")


# ── collect command output ──

class RepoSignal(BaseModel):
    """A single repo signal from the collect command."""
    full_name: str = Field(description="GitHub repository full name, e.g. 'langchain-ai/langchain'")
    owner: str = Field(description="Repository owner (user or organization)")
    stars: int = Field(default=0, description="Stargazer count at collection time")
    forks: int = Field(default=0, description="Fork count")
    contributors: int = Field(default=0, description="Contributor count (always 0 — GitHub Search API limitation. Reserved for future enhancement.)")
    velocity: float = Field(default=0.0, description="Stars per day growth rate. Used by trend engine for hotness calculation.")
    topics: list[str] = Field(default_factory=list, description="GitHub topic tags. Used by trend engine for topic-based aggregation.")
    description: str = Field(default="", description="Repository description from GitHub")
    language: str = Field(default="", description="Primary programming language")
    created_at: str = Field(default="", description="Repository creation date (ISO 8601)")


class IssueSignal(BaseModel):
    """A single issue signal from the collect command."""
    repo: str = Field(description="Repository full name where this issue was opened")
    issue_number: int = Field(description="GitHub issue number")
    title: str = Field(description="Issue title")
    body: str = Field(default="", description="Issue body text. Used by pain command for embedding-based clustering.")
    comments: int = Field(default=0, description="Number of comments on the issue")
    participants: int = Field(default=0, description="Number of unique participants in the issue discussion")
    reactions: int = Field(default=0, description="Total reaction count (sum of all reaction types)")
    labels: list[str] = Field(default_factory=list, description="GitHub issue labels. Used for demand signal filtering.")
    url: str = Field(default="", description="Full GitHub issue URL")


class CollectPayload(BaseModel):
    """Payload for collect command output.

    repos and issues are flat, human-readable output contracts.
    signals is the normalized form (Signal JSON dicts) for direct
    consumption by downstream commands — no re-normalization needed.
    """
    repos: list[RepoSignal] = Field(default_factory=list, description="Flat list of repo signal objects for human reading and report rendering")
    issues: list[IssueSignal] = Field(default_factory=list, description="Flat list of issue signal objects with demand filtering applied")
    signals: list[dict[str, Any]] = Field(default_factory=list, description="Normalized Signal objects serialized as JSON dicts — the canonical format consumed by trend, pain, and opportunity commands")


# ── trend command output ──

class RepoSummary(BaseModel):
    """Trend command's repo summary."""
    full_name: str = Field(description="Repository full name")
    stars: int = Field(description="Star count")
    stars_delta: int = Field(default=0, description="Star change within the analysis window")
    forks: int = Field(description="Fork count")
    contributors: int = Field(default=0, description="Contributor count (same limitation as RepoSignal.contributors)")
    velocity: float = Field(description="Stars/day growth rate")
    description: str = Field(default="", description="Repository description")


class TopicTrend(BaseModel):
    """A single topic trend from the trend command."""
    topic: str = Field(description="Topic name (e.g. 'mcp', 'langchain', 'agent-framework')")
    stage: Literal["accelerating", "emerging", "mainstream", "declining"] = Field(description="Lifecycle stage based on velocity + acceleration thresholds")
    confidence: float = Field(description="Confidence score (0-1). Low confidence (<0.3) means insufficient evidence — treat conclusion as tentative.")
    growth_velocity: float = Field(description="Weighted average star velocity across repos in this topic")
    acceleration: float = Field(default=0.0, description="Rate of velocity change. >2.0 + high confidence → 'accelerating'; <-1.0 → 'declining'.")
    evidence_count: int = Field(description="Number of repos contributing to this trend. <3 means low confidence.")
    top_repos: list[RepoSummary] = Field(default_factory=list, description="Top 5 repos by stars within this topic")
    classification_reason: str = Field(
        default="",
        description="Why this stage was assigned (e.g. 'acceleration=3.2 (>2.0) + confidence=0.8 (>0.6) → accelerating')",
    )


class TrendPayload(BaseModel):
    """Payload for trend command output."""
    trends: list[TopicTrend] = Field(default_factory=list, description="Ranked list of topic trends, sorted by growth_velocity descending")
    domain: str = Field(description="Domain these trends belong to")
    window_days: int = Field(description="Analysis time window in days used for velocity calculation")


# ── pain command output ──

class IssueSummary(BaseModel):
    """Pain command's issue summary."""
    repo: str = Field(description="Repository full name")
    issue_number: int = Field(description="GitHub issue number")
    title: str = Field(description="Issue title")
    pain_score: float = Field(description="Composite pain score: severity × frequency × engagement. Higher = more user pain.")


class PainCluster(BaseModel):
    """A single pain cluster from the pain command."""
    cluster_id: int = Field(description="HDBSCAN cluster ID")
    title: str = Field(description="Human-readable cluster title summarizing the pain theme")
    severity: float = Field(description="Average severity score across issues in this cluster (0-10)")
    frequency: int = Field(description="Number of issues in this cluster")
    affected_repos: list[str] = Field(default_factory=list, description="Repositories affected by this pain cluster")
    top_issues: list[IssueSummary] = Field(default_factory=list, description="Representative issues with highest pain scores")


class PainPayload(BaseModel):
    """Payload for pain command output."""
    clusters: list[PainCluster] = Field(default_factory=list, description="Discovered pain clusters, sorted by severity descending")
    issue_count: int = Field(default=0, description="Total number of issues analyzed")
    repos_analyzed: list[str] = Field(default_factory=list, description="List of repositories whose issues were analyzed")


# ── opportunity command output ──

class OpportunityCard(BaseModel):
    """A single opportunity from the rule-engine scorer."""
    title: str = Field(description="Opportunity title: '<topic> — gap=<gap_score>'")
    demand_score: float = Field(description="Aggregate demand signal from trends + pain clusters (0-10)")
    competition_score: float = Field(description="Competition intensity from existing repo activity (0-10)")
    gap_score: float = Field(description="Opportunity gap = demand_score / max(0.1, competition_score). Higher = more underserved demand.")
    signals: list[str] = Field(default_factory=list, description="Supporting evidence: top repos and representative issues")
    recommended_action: str = Field(default="", description="Suggested next action: 'Build', 'Monitor', 'Avoid', or 'Partner'")
    # Personalized fields added by alignment engine (User DNA integration)
    personalized_score: float | None = Field(default=None, description="gap_score × alignment_multiplier. Null when User DNA is unavailable.")
    alignment_reason: str = Field(default="", description="Why this opportunity matches user values (empty when not personalized)")
    alignment_multiplier: float = Field(default=1.0, description="Raw multiplier from User DNA alignment. 1.0 = neutral, >1.0 = strong match, <1.0 = mismatch.")
    scoring_breakdown: dict = Field(
        default_factory=dict,
        description="Decomposed scoring: velocity_contribution, severity_contribution, frequency_contribution, demand_score, competition_score, gap_formula",
    )


class OpportunityPayload(BaseModel):
    """Payload for opportunity command output."""
    opportunities: list[OpportunityCard] = Field(default_factory=list, description="Ranked opportunity cards, sorted by personalized_score (fallback: gap_score)")
